version: "3.7"
services:
  documentation:
    image: swaggerapi/swagger-ui
    ports:
      - "5000:8080"
    environment:
      - "SWAGGER_JSON=/docs/BeneficiaryAPI.Swagger20.json"
    volumes:
      - "./docs:/docs"
  mysql:
    image: mysql:8.0.25
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=123"
      - "MYSQL_DATABASE=dev_test"
  app:
    image: beneficiary-api:test
    depends_on:
      - "mysql"
    ports:
      - "3000:3000"
    environment:
      - "DB_NAME=dev_test"
      - "DB_USER=root"
      - "DB_PASSWORD=123"
      - "DB_HOST=mysql"
      - "DB_PORT=3306"
      - "AUTH_TOKEN=test_token"
      - "DATABASE_DELAY=15000"
